# ─── S3 Module — Variables ─────────────────────────────────────────────────────

variable "aws_region" {
  description = "AWS region for the S3 bucket."
  type        = string
  default     = "us-east-1"
}

variable "bucket_name" {
  description = <<-EOT
    Full S3 bucket name. Must be globally unique across all AWS accounts.
    Generated by the provisioning service as:
      cloudprovision-<userId>-<timestamp>-<random>
    Do NOT hardcode a bucket name — collisions will cause provisioning to fail.
  EOT
  type        = string
}

variable "job_id" {
  description = "CloudProvision job ID — used as a tag for resource tracking."
  type        = string
}

variable "user_id" {
  description = "CloudProvision user ID — used as a tag for ownership tracking."
  type        = string
}
