# ─── S3 Module — Variables ─────────────────────────────────────────────────────

variable "aws_region" {
  description = "AWS region for the S3 bucket."
  type        = string
  default     = "us-east-1"
}

variable "bucket_name" {
  description = <<-EOT
    Full S3 bucket name. Must be globally unique across all AWS accounts.
    Generated by the provisioning service as:
      cloudprovision-<userId_short>-<timestamp>-<random>
    Do NOT hardcode — collisions cause provisioning to fail.
  EOT
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9][a-z0-9\\-]{1,61}[a-z0-9]$", var.bucket_name))
    error_message = "bucket_name must be 3–63 lowercase letters, numbers, or hyphens, and must start/end with a letter or number."
  }
}

variable "versioning_enabled" {
  description = "Enable S3 bucket versioning."
  type        = bool
  default     = false
}

variable "job_id" {
  description = "CloudProvision job ID — tag for resource tracking."
  type        = string

  validation {
    condition     = length(var.job_id) > 0
    error_message = "job_id must not be empty."
  }
}

variable "user_id" {
  description = "CloudProvision user ID — tag for ownership tracking."
  type        = string

  validation {
    condition     = length(var.user_id) > 0
    error_message = "user_id must not be empty."
  }
}
