# ─── RDS Module — Variables ────────────────────────────────────────────────────

variable "aws_region" {
  description = "AWS region for the RDS instance."
  type        = string
  default     = "us-east-1"
}

variable "db_identifier" {
  description = "Unique identifier for the RDS DB instance."
  type        = string

  validation {
    condition     = can(regex("^[a-z][a-z0-9\\-]{0,62}$", var.db_identifier))
    error_message = "db_identifier must start with a letter, contain only lowercase letters, numbers, and hyphens, and be 1–63 characters."
  }
}

variable "db_engine" {
  description = "Database engine."
  type        = string
  default     = "mysql"

  validation {
    condition     = contains(["mysql", "postgres"], var.db_engine)
    error_message = "db_engine must be 'mysql' or 'postgres'."
  }
}

variable "db_engine_version" {
  description = "Engine version. Leave blank to use a sensible default per engine."
  type        = string
  default     = ""
}

variable "db_instance_class" {
  description = "RDS instance class."
  type        = string
  default     = "db.t3.micro"

  validation {
    condition     = contains(["db.t3.micro", "db.t3.small"], var.db_instance_class)
    error_message = "db_instance_class must be db.t3.micro or db.t3.small."
  }
}

variable "db_allocated_storage" {
  description = "Allocated storage in GB (minimum 20)."
  type        = number
  default     = 20

  validation {
    condition     = var.db_allocated_storage >= 20 && var.db_allocated_storage <= 100
    error_message = "db_allocated_storage must be between 20 and 100 GB."
  }
}

variable "db_name" {
  description = "Name of the initial database."
  type        = string
  default     = "appdb"

  validation {
    condition     = can(regex("^[a-zA-Z][a-zA-Z0-9_]{0,63}$", var.db_name))
    error_message = "db_name must start with a letter and contain only letters, numbers, and underscores."
  }
}

variable "db_username" {
  description = "Master username for the database."
  type        = string
  sensitive   = true

  validation {
    condition     = length(var.db_username) >= 1 && length(var.db_username) <= 16
    error_message = "db_username must be 1–16 characters."
  }
}

variable "db_password" {
  description = <<-EOT
    Master password for the database.
    SECURITY: This value is stored in Terraform state. The state file must be
    secured and never committed to version control (it is gitignored).
    Generated by the provisioning service at runtime — never hardcoded.
  EOT
  type        = string
  sensitive   = true

  validation {
    condition     = length(var.db_password) >= 8
    error_message = "db_password must be at least 8 characters."
  }
}

variable "multi_az" {
  description = "Enable Multi-AZ for high availability. Not recommended for demo (higher cost)."
  type        = bool
  default     = false
}

variable "job_id" {
  description = "CloudProvision job ID."
  type        = string

  validation {
    condition     = length(var.job_id) > 0
    error_message = "job_id must not be empty."
  }
}

variable "user_id" {
  description = "CloudProvision user ID."
  type        = string

  validation {
    condition     = length(var.user_id) > 0
    error_message = "user_id must not be empty."
  }
}
